# Generated by Django 4.1 on 2023-04-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='la',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='mian',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='qindan',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='tang',
        ),
    ]
