# Generated by Django 4.1 on 2023-04-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_userinfo_la_remove_userinfo_mian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('intro', models.CharField(max_length=64)),
                ('score', models.CharField(max_length=32)),
                ('class1', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to='img_url')),
            ],
        ),
    ]
