# Generated by Django 4.1 on 2023-04-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_mypicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mypicture',
        ),
        migrations.AddField(
            model_name='food_list',
            name='method1',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='food_list',
            name='class1',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='food_list',
            name='intro',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='food_list',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='food_list',
            name='photo',
            field=models.ImageField(default='user1.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='food_list',
            name='score',
            field=models.CharField(default='', max_length=32),
        ),
    ]
