# Generated by Django 4.1 on 2023-04-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_delete_mypicture_food_list_method1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food_list',
            new_name='Foodlist',
        ),
    ]
