# Generated by Django 4.1 on 2023-04-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_mypicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='food_list',
        ),
        migrations.AddField(
            model_name='mypicture',
            name='class1',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mypicture',
            name='intro',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mypicture',
            name='method1',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='mypicture',
            name='score',
            field=models.CharField(default='', max_length=32),
        ),
    ]
