# Generated by Django 4.1 on 2023-04-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_delete_food_list_mypicture_class1_mypicture_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypicture',
            name='method1',
            field=models.CharField(default='', max_length=32),
        ),
    ]
