# Generated by Django 4.1 on 2023-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_mypicture_method1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypicture',
            name='method1',
            field=models.CharField(default='', max_length=300),
        ),
    ]
