# Generated by Django 4.1 on 2023-05-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_rename_name1_userinfo1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypicture',
            name='class2',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mypicture',
            name='country',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mypicture',
            name='taste',
            field=models.CharField(default='', max_length=32),
        ),
    ]
