# Generated by Django 4.1 on 2023-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_alter_mypicture_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypicture',
            name='save_num',
            field=models.CharField(default='', max_length=300),
        ),
    ]
