# Generated by Django 4.1 on 2023-05-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_mypicture_save_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypicture',
            name='save_num',
            field=models.IntegerField(default='', max_length=100),
        ),
    ]
