# Generated by Django 4.1 on 2023-05-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_alter_mypicture_save_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=64)),
                ('user_id', models.CharField(default='', max_length=64)),
                ('food_id', models.CharField(default='', max_length=64)),
                ('food_name', models.CharField(default='', max_length=300)),
                ('user_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=64)),
                ('user_photo', models.CharField(default='', max_length=64)),
                ('user_id', models.CharField(default='', max_length=64)),
                ('food_id', models.CharField(default='', max_length=64)),
                ('food_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='mypicture',
            name='save_num',
            field=models.IntegerField(default=''),
        ),
    ]
