# Generated by Django 4.1 on 2023-05-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_motivation_user_save_alter_mypicture_save_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_save',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='user_save',
            name='user_id',
        ),
    ]
