# Generated by Django 4.1 on 2023-05-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_remove_user_save_food_id_remove_user_save_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_save',
            old_name='user_photo',
            new_name='food_photo',
        ),
    ]
