# Generated by Django 4.1 on 2023-05-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_motivation_food_comment_user_save_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivation',
            name='user_id',
        ),
    ]
