# Generated by Django 4.1 on 2023-05-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_mypicture_main_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='user_score',
            field=models.FloatField(),
        ),
    ]
